language: node_js
node_js:
  - "11.10.1"
install:
  - npm install
before_script: 
  - export COVERAGE_TOKEN=$COVERAGE_TOKEN
  - export HEROKU_KEY=$HEROKU_KEY
deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: d13backend
  on: master 
  strategy: git
  run:
    - "npm run db:migrate"